name: Deploy website

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install tracery requests flair jinja2
      - name: Commit index.html
        run: |
          git config --local user.email "jamesg@jamesg.blog"
          git config --local user.name "capjamesg"
          git add index.html
          git commit -m "update index.html"
          git push
